services:
    # Doctrine Event Subscriber
    doctrine_event_subscriber:
        class: EventBundle\Event\Subscriber\DoctrineSubscriber
        arguments:
            - "@delayed_event_dispatcher"
        tags:
            - { name: doctrine.event_subscriber, connection: default }
