services:
    # Delayed dispatcher
    delayed_event_dispatcher:
        class: EventBundle\Event\Dispatcher\DelayedEventDispatcher
        arguments:
            - "@service_container"
        tags:
            - { name: kernel.event_subscriber }
