services:
    # Delayed Event Dispatcher
    delayed_event_dispatcher:
        class: EventBundle\Event\Dispatcher\DelayedEventDispatcher
        arguments:
            - "@event_dispatcher"
        tags:
            - { name: kernel.event_subscriber }

    # Doctrine Event Subscriber
    doctrine_event_subscriber:
        class: EventBundle\Event\Subscriber\DoctrineSubscriber
        arguments:
            - "@delayed_event_dispatcher"
        tags:
            - { name: doctrine.event_subscriber, connection: default }
